### ISSUE TITLE
Behaviour of row/column restriction

### ISSUE THREAD

**Issue by nbrr** [rcarson3/rust_data_reader#3]
The `num_lines` and `num_fields` fields in the `ReaderResults` don't scale consistently to the result when the `ReaderParams` restricts the lines/fields to be read.

input: a 5*8 matrix
```
1,2,3,4,5,6,7,8
1,2,3,4,5,6,7,8
1,2,3,4,5,6,7,8
1,2,3,4,5,6,7,8
1,2,3,4,5,6,7,8

```

# No restriction
```
    let source = "mat.txt";

    let params = ReaderParams {
        comments: b'%',
        delimiter: Delimiter::Any(b','),
        skip_header: None,
        skip_footer: None,
        usecols: None,
        max_rows: None,
    };

    let input = load_txt_i64(&source, &params).unwrap();
    println!("{:?}", input);
```
    ReaderResults { num_fields: 8, num_lines: 5, results: [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8] }

`num_*` match the dimension of the matrix.

# Row restriction
`    max_rows: Some(2),`

    ReaderResults { num_fields: 8, num_lines: 2, results: [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8] }
**`num_lines` scales**

# Column restriction
## Sane column numbers
        usecols: Some(vec![1, 4]),

    ReaderResults { num_fields: 8, num_lines: 5, results: [1, 4, 1, 4, 1, 4, 1, 4, 1, 4] }
**`num_fields` does not scale**

## Inconsistent column numbers
`    usecols: Some(vec![0, 10, 11]),`

    ReaderResults { num_fields: 8, num_lines: 5, results: [] }
inconsistent column numbers are ignored, **`num_fields` does not scale** and **result is empty**, moreover **column indexing starts at 1** and not 0 as one would probably expect in Rust context in absence of further documentation

**Comment by rcarson3** [comment]
Documentation has now been updated to mention the 1 indexing feature. Also, the bugs mentioned should now all be captured as of commit [b834892](https://github.com/rcarson3/rust_data_reader/commit/b83489203d93768e9475a76aed132c29d2b16344). I'll push a new point release later tonight once I'm able to add some simple ReaderParam constructors.

**Comment by rcarson3** [comment]
@nbrr I'm probably going to update the column indexing to 0. The new getter functions I added for #4 are all based on 0 indexing, so it just makes since to change this over to 0 indexing as well. It'll also make things more idiomatic with most other rust code as well. Since I have to push a point release for those changes anyways due to there being breaking changes by adding an additional trait requirement for the ```ReaderResults``` struct, it just makes sense to go ahead and add another breaking change as well in there to make things nicer.

**Comment by rcarson3** [comment]
This took way longer than it should have due to work and life, but the master branch now has the columns set as being 0 indexed.
