### ISSUE TITLE
Method to access a data in the result

### ISSUE THREAD

**Issue by nbrr** [rcarson3/rust_data_reader#4]
Reader functions provided in the crate parse a 2 dimensional array, but the result is given as a 1 dimensional vector. It would make sense to provide a method to access data from its (line, column) indices in the original array.

**Comment by rcarson3** [comment]
@nbrr Sorry for taking so long to get this added. I've been busy with work and a few other things. If you check the current master branch you should be able to see that I've added a ```get_value()```, ```get_row()```, and ```get_col()``` functions to the ```ReaderResults``` struct. Let me know what you think of these. I'm also considering adding a ```get_rows()``` and ```get_cols()``` set of functions that return ```Vec<Vec<T>>``` for the results. I don't think these should be that hard to add either. 

If you like the above let me know and I'll add those functions to everything. I'll probably then push out a new point release with these changes to crates.io as well.

Edit: A simple version of the ```get_rows()``` and ```get_cols()``` has now been added as well.

**Comment by rcarson3** [comment]
The point release with these fixes will be coming within the next week.
