### ISSUE TITLE
Have `ReaderParams`' `comment` as an option

### ISSUE THREAD

**Issue by nbrr** [rcarson3/rust_data_reader#5]
Since the inputs don't always bear comments, I think it would be cleaner for the comment marker field in `ReaderParams` to be an `Option<u8>`, otherwise one needs to pick a random filler for this.

**Comment by rcarson3** [comment]
Added this ability in commit [df56ef9](https://github.com/rcarson3/rust_data_reader/commit/df56ef98cdd724c9b679a98669846f581c8f6104). I've still set set the default to being # to keep things inline with numpy's default value.
