### ISSUE TITLE
Simple `ReaderParams` builders

### ISSUE THREAD

**Issue by nbrr** [rcarson3/rust_data_reader#7]
If one only needs basic functionality, functions building `ReaderParams` would allow a more readable code.

```
ReaderParams {
    comments: b'%',
    delimiter: Delimiter::Any(b','),
    skip_header: None,
    skip_footer: None,
    usecols: None,
    max_rows: None,
};
```
e.g.
- parse a separated values file `delimiter(d: u8) -> ReaderParams`
- take the n first lines `head(d: u8, n: usize) -> ReaderParams`

**Comment by rcarson3** [comment]
So, I'm going to leave this open but with the Default constructor existing the current way to do this is fairly compact for example the delimiter example is just:

```Rust
ReaderParams{
    delimiter: Delimiter::Any(u8),
    ..Default::default()
}
```

Then if you want just the default values it's just:

```
ReaderParams::default()
```

I did start looking into a few new constructors, but then I started thinking about what simple versions people might like. I realized there could be lots of different opinions here, and I'd like to hear from at least a few people before adding any simple new constructors. I do agree that if we find people are using lots of common patterns then some easy to use constructors will make things a lot cleaner.
